### ISSUE TITLE
nextdns client on edgeos crashes with error: panic: runtime error: makeslice: len out of range

### ISSUE THREAD

**Issue by gbil** [nextdns/nextdns#159]
Hi,
the nextdns clients crashes many times with the following behavior:

- replies come it with: doh resolve: context deadline exceeded 
- then this is registered in the log: panic: runtime error: makeslice: len out of range
followed by:

```
Apr 18 08:37:01 ubnt nextdns[1853]: goroutine 837192 [running]:
Apr 18 08:37:01 ubnt nextdns[1853]: github.com/nextdns/nextdns/resolver.(*DOH).resolve(0xc0000ffb00, 0x547580, 0xc000432720, 0x49160001000c0000, 0xc000bb4160, 0x1c, 0xc0009b024c, 0x10, 0x10, 0xc0003587e0, ...)
Apr 18 08:37:01 ubnt nextdns[1853]:         /home/runner/work/nextdns/nextdns/resolver/doh.go:126 +0x64c
Apr 18 08:37:01 ubnt nextdns[1853]: github.com/nextdns/nextdns/resolver.(*DNS).Resolve.func1(0x547700, 0xc0003016e0, 0x2, 0xc000108a68)
Apr 18 08:37:01 ubnt nextdns[1853]:         /home/runner/work/nextdns/nextdns/resolver/resolver.go:77 +0x178
Apr 18 08:37:01 ubnt nextdns[1853]: github.com/nextdns/nextdns/resolver/endpoint.(*activeEnpoint).do(0xc000301740, 0xc00053f9d8, 0x0, 0x0)
Apr 18 08:37:01 ubnt nextdns[1853]:         /home/runner/work/nextdns/nextdns/resolver/endpoint/manager.go:315 +0x6c
Apr 18 08:37:01 ubnt nextdns[1853]: github.com/nextdns/nextdns/resolver/endpoint.(*Manager).Do(0xc000108a00, 0x547580, 0xc000432720, 0xc00053f9d8, 0x2e62616d67726964, 0x2e636f6d2e646973)
Apr 18 08:37:01 ubnt nextdns[1853]:         /home/runner/work/nextdns/nextdns/resolver/endpoint/manager.go:235 +0x6c
Apr 18 08:37:01 ubnt nextdns[1853]: github.com/nextdns/nextdns/resolver.(*DNS).Resolve(0xc0000ffb00, 0x547580, 0xc000432720, 0x49160001000c0000, 0xc000bb4160, 0x1c, 0xc0009b024c, 0x10, 0x10, 0xc0003587e0, ...)
Apr 18 08:37:01 ubnt nextdns[1853]:         /home/runner/work/nextdns/nextdns/resolver/resolver.go:73 +0xd4
Apr 18 08:37:01 ubnt nextdns[1853]: github.com/nextdns/nextdns/config.(*Forwarders).Resolve(0xc00011a0a0, 0x547580, 0xc000432720, 0x49160001000c0000, 0xc000bb4160, 0x1c, 0xc0009b024c, 0x10, 0x10, 0xc0003587e0, ...)
Apr 18 08:37:01 ubnt nextdns[1853]:         /home/runner/work/nextdns/nextdns/config/forwarder.go:112 +0xa8
Apr 18 08:37:01 ubnt nextdns[1853]: github.com/nextdns/nextdns/proxy.Proxy.Resolve(0x4a2fe0, 0x3, 0x53fda0, 0xc00011a0a0, 0x101000000000000, 0x12a05f200, 0xc00011a0c0, 0xc00011a0e0, 0xc00011a100, 0x547580, ...)
Apr 18 08:37:01 ubnt nextdns[1853]:         /home/runner/work/nextdns/nextdns/proxy/proxy.go:155 +0x124
Apr 18 08:37:01 ubnt nextdns[1853]: github.com/nextdns/nextdns/proxy.Proxy.serveUDP.func2(0xc000c82600, 0x2d, 0xc000bd6600, 0x4a2fe0, 0x3, 0x53fda0, 0xc00011a0a0, 0x101000000000000, 0x12a05f200, 0xc00011a0c0, ...)
Apr 18 08:37:01 ubnt nextdns[1853]:         /home/runner/work/nextdns/nextdns/proxy/udp.go:102 +0x2b4
Apr 18 08:37:01 ubnt nextdns[1853]: created by github.com/nextdns/nextdns/proxy.Proxy.serveUDP
Apr 18 08:37:01 ubnt nextdns[1853]:         /home/runner/work/nextdns/nextdns/proxy/udp.go:71 +0x278
Apr 18 08:37:01 ubnt systemd[1]: nextdns.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 18 08:37:01 ubnt systemd[1]: nextdns.service: Unit entered failed state.
Apr 18 08:37:01 ubnt systemd[1]: nextdns.service: Failed with result 'exit-code'.
```

This happens almost every day. During the error period Internet connectivity is not dropped so that is not the root cause

**Comment by rs** [comment]
Which version are you running? Can you please try to upgrade?

**Comment by rsyring** [comment]
I had the same issue this morning when resuming my Ubuntu Eoan laptop from suspend.  I was running v1.5.1.  I'm upgrading to 1.5.2 now.  Logs below for context in case it helps later:

```
Apr 19 13:02:52 nanex nextdns[14005]: Network change detected: enp0s31f6 down
Apr 19 13:02:57 nanex nextdns[14005]: Endpoint provider failed: https://router.nextdns.io?stack=dual: Get "https://216.239.32.21:443?stack=dual": net/http: re
Apr 19 13:02:58 nanex nextdns[14005]: Connected 45.90.28.0:443 (con=276ms tls=312ms, TLS13)
Apr 19 13:02:58 nanex nextdns[14005]: Switching endpoint: https://dns1.nextdns.io#45.90.28.0,2a07:a8c0::
Apr 19 13:03:01 nanex nextdns[14005]: Network change detected: enp0s31f6 up
Apr 19 13:03:04 nanex nextdns[14005]: Endpoint failed: https://vultr-chi-1.edge.nextdns.io#144.202.56.172,2001:19f0:5c01:7a5:5400:2ff:fe99:94f9: roundtrip: co
Apr 19 13:03:10 nanex nextdns[14005]: Endpoint failed: https://vultr-chi-1.edge.nextdns.io#144.202.56.172,2001:19f0:5c01:7a5:5400:2ff:fe99:94f9: roundtrip: co
Apr 19 13:03:16 nanex nextdns[14005]: Endpoint failed: https://vultr-chi-1.edge.nextdns.io#144.202.56.172,2001:19f0:5c01:7a5:5400:2ff:fe99:94f9: roundtrip: co
Apr 19 13:03:16 nanex nextdns[14005]: panic: runtime error: makeslice: len out of range
Apr 19 13:03:16 nanex nextdns[14005]: goroutine 39020 [running]:
Apr 19 13:03:16 nanex nextdns[14005]: github.com/nextdns/nextdns/resolver.(*DOH).resolve(0xc0000e42d0, 0x8e67c0, 0xc00067efc0, 0x1c00012204, 0xc00025fe80, 0x1
Apr 19 13:03:16 nanex nextdns[14005]:         /home/runner/work/nextdns/nextdns/resolver/doh.go:126 +0x750
Apr 19 13:03:16 nanex nextdns[14005]: github.com/nextdns/nextdns/resolver.(*DNS).Resolve.func1(0x8e6980, 0xc0000a8420, 0xc000405970, 0x2)
Apr 19 13:03:16 nanex nextdns[14005]:         /home/runner/work/nextdns/nextdns/resolver/resolver.go:77 +0x1cb
Apr 19 13:03:16 nanex nextdns[14005]: github.com/nextdns/nextdns/resolver/endpoint.(*activeEnpoint).do(0xc000064420, 0xc0004059c0, 0x0, 0x0)
Apr 19 13:03:16 nanex nextdns[14005]:         /home/runner/work/nextdns/nextdns/resolver/endpoint/manager.go:315 +0x59
Apr 19 13:03:16 nanex nextdns[14005]: github.com/nextdns/nextdns/resolver/endpoint.(*Manager).Do(0xc0000b4dc0, 0x8e67c0, 0xc00067efc0, 0xc0004059c0, 0x2e6e616
Apr 19 13:03:16 nanex nextdns[14005]:         /home/runner/work/nextdns/nextdns/resolver/endpoint/manager.go:235 +0x5b
Apr 19 13:03:16 nanex nextdns[14005]: github.com/nextdns/nextdns/resolver.(*DNS).Resolve(0xc0000e42d0, 0x8e67c0, 0xc00067efc0, 0x1c00012204, 0xc00025fe80, 0x1
Apr 19 13:03:16 nanex nextdns[14005]:         /home/runner/work/nextdns/nextdns/resolver/resolver.go:73 +0x13a
Apr 19 13:03:16 nanex nextdns[14005]: github.com/nextdns/nextdns/config.(*Forwarders).Resolve(0xc00009a500, 0x8e67c0, 0xc00067efc0, 0x1c00012204, 0xc00025fe80
Apr 19 13:03:16 nanex nextdns[14005]:         /home/runner/work/nextdns/nextdns/config/forwarder.go:112 +0xde
Apr 19 13:03:16 nanex nextdns[14005]: github.com/nextdns/nextdns/proxy.Proxy.Resolve(0xc0000c4687, 0xc, 0x8deee0, 0xc00009a500, 0x101, 0x12a05f200, 0x0, 0xc00
Apr 19 13:03:16 nanex nextdns[14005]:         /home/runner/work/nextdns/nextdns/proxy/proxy.go:155 +0x19b
Apr 19 13:03:16 nanex nextdns[14005]: github.com/nextdns/nextdns/proxy.Proxy.serveUDP.func2(0xc000500880, 0x22, 0xc0003a5ce0, 0xc0000c4687, 0xc, 0x8deee0, 0xc
Apr 19 13:03:16 nanex nextdns[14005]:         /home/runner/work/nextdns/nextdns/proxy/udp.go:102 +0x42a
Apr 19 13:03:16 nanex nextdns[14005]: created by github.com/nextdns/nextdns/proxy.Proxy.serveUDP
Apr 19 13:03:16 nanex nextdns[14005]:         /home/runner/work/nextdns/nextdns/proxy/udp.go:71 +0x2d4
Apr 19 13:03:16 nanex systemd[1]: nextdns.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 19 13:03:16 nanex systemd[1]: nextdns.service: Failed with result 'exit-code'.
```

**Comment by rs** [comment]
Please tell me if it’s still happening with 1.5.2.

**Comment by rs** [comment]
Please reopen if you still get a crash on latest release.

**Comment by rsyring** [comment]
FYI, this is still an issue with v1.5.2.  I just received the below stack trace when waking from sleep.  My network connection is bouncing as part of the sleep/resume process:

```
Apr 23 20:33:07 nanex nextdns[2763]: Endpoint provider failed: https://router.nextdns.io?stack=dual: Get "https://216.239.32.21:443?stack=dual": context deadline exceeded (Client.Timeout exc
Apr 23 20:33:09 nanex nextdns[2763]: Connected 45.90.28.0:443 (con=621ms tls=482ms, TLS13)
Apr 23 20:33:09 nanex nextdns[2763]: Switching endpoint: https://dns1.nextdns.io#45.90.28.0,2a07:a8c0::
Apr 23 20:33:12 nanex nextdns[2763]: panic: runtime error: makeslice: len out of range
Apr 23 20:33:12 nanex nextdns[2763]: goroutine 35002 [running]:
Apr 23 20:33:12 nanex nextdns[2763]: github.com/nextdns/nextdns/resolver.(*DOH).resolve(0xc0001642d0, 0x8e8d60, 0xc000129500, 0x1c0001f3ca, 0xc000449560, 0x1f, 0xc000449448, 0x4, 0x4, 0x0, .
Apr 23 20:33:12 nanex nextdns[2763]:         /home/runner/work/nextdns/nextdns/resolver/doh.go:126 +0x750
Apr 23 20:33:12 nanex nextdns[2763]: github.com/nextdns/nextdns/resolver.(*DNS).Resolve.func1(0x8e8f20, 0xc0001284e0, 0xc0001e9970, 0x2)
Apr 23 20:33:12 nanex nextdns[2763]:         /home/runner/work/nextdns/nextdns/resolver/resolver.go:77 +0x1cb
Apr 23 20:33:12 nanex nextdns[2763]: github.com/nextdns/nextdns/resolver/endpoint.(*activeEnpoint).do(0xc0006b4300, 0xc0001e99c0, 0x0, 0x0)
Apr 23 20:33:12 nanex nextdns[2763]:         /home/runner/work/nextdns/nextdns/resolver/endpoint/manager.go:315 +0x59
Apr 23 20:33:12 nanex nextdns[2763]: github.com/nextdns/nextdns/resolver/endpoint.(*Manager).Do(0xc000134d20, 0x8e8d60, 0xc000129500, 0xc0001e99c0, 0x2e6e616c2e, 0x0)
Apr 23 20:33:12 nanex nextdns[2763]:         /home/runner/work/nextdns/nextdns/resolver/endpoint/manager.go:235 +0x5b
Apr 23 20:33:12 nanex nextdns[2763]: github.com/nextdns/nextdns/resolver.(*DNS).Resolve(0xc0001642d0, 0x8e8d60, 0xc000129500, 0x1c0001f3ca, 0xc000449560, 0x1f, 0xc000449448, 0x4, 0x4, 0x0, .
Apr 23 20:33:12 nanex nextdns[2763]:         /home/runner/work/nextdns/nextdns/resolver/resolver.go:73 +0x13a
Apr 23 20:33:12 nanex nextdns[2763]: github.com/nextdns/nextdns/config.(*Forwarders).Resolve(0xc00011c500, 0x8e8d60, 0xc000129500, 0x1c0001f3ca, 0xc000449560, 0x1f, 0xc000449448, 0x4, 0x4, 0
Apr 23 20:33:12 nanex nextdns[2763]:         /home/runner/work/nextdns/nextdns/config/forwarder.go:112 +0xde
Apr 23 20:33:12 nanex nextdns[2763]: github.com/nextdns/nextdns/proxy.Proxy.Resolve(0xc0001445e7, 0xc, 0x8e13a0, 0xc00011c500, 0x101, 0x12a05f200, 0x0, 0xc00011c520, 0xc00011c540, 0x8e8d60, 
Apr 23 20:33:12 nanex nextdns[2763]:         /home/runner/work/nextdns/nextdns/proxy/proxy.go:155 +0x19b
Apr 23 20:33:12 nanex nextdns[2763]: github.com/nextdns/nextdns/proxy.Proxy.serveUDP.func2(0xc0003f24c0, 0x30, 0xc0004639b0, 0xc0001445e7, 0xc, 0x8e13a0, 0xc00011c500, 0x101, 0x12a05f200, 0x
Apr 23 20:33:12 nanex nextdns[2763]:         /home/runner/work/nextdns/nextdns/proxy/udp.go:102 +0x42a
Apr 23 20:33:12 nanex nextdns[2763]: created by github.com/nextdns/nextdns/proxy.Proxy.serveUDP
Apr 23 20:33:12 nanex nextdns[2763]:         /home/runner/work/nextdns/nextdns/proxy/udp.go:71 +0x2d4
Apr 23 20:33:12 nanex systemd[1]: nextdns.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 23 20:33:12 nanex systemd[1]: nextdns.service: Failed with result 'exit-code'.
```

Reopen?

**Comment by gbil** [comment]
got exactly the same thing, good to see another fix for it
is it possible to release a new version soon as I don't know who to compile this for edgeos?

**Comment by rs** [comment]
1.5.3 is out
