### ISSUE TITLE
panic: runtime error: makeslice: len out of range

### ISSUE THREAD

**Issue by inoperable** [nextdns/nextdns#181]
Hello, 

I started to see this error in logs recently
```
Apr 27 04:13:07 *REDACTED* systemd[1]: Started NextDNS DNS53 to DoH proxy..
Apr 27 09:55:27 *REDACTED* nextdns[2324]: panic: runtime error: makeslice: len out of range
Apr 27 09:55:27 *REDACTED* nextdns[2324]: goroutine 231044 [running]:
Apr 27 09:55:27 *REDACTED* nextdns[2324]: github.com/nextdns/nextdns/resolver.(*DOH).resolve(0xc0000ce240, 0x56533e01ee20, 0xc0099c9560, 0x10001f52d, 0xc0003c4c20, 0xf, 0xc00069e168, 0x4, 0x4, 0x0, ...)
Apr 27 09:55:27 *REDACTED* nextdns[2324]:         github.com/nextdns/nextdns/resolver/doh.go:126 +0x752
Apr 27 09:55:27 *REDACTED* nextdns[2324]: github.com/nextdns/nextdns/resolver.(*DNS).Resolve.func1(0x56533e01efe0, 0xc0000205a0, 0x203002, 0xc000323ab8)
Apr 27 09:55:27 *REDACTED* nextdns[2324]:         github.com/nextdns/nextdns/resolver/resolver.go:77 +0x1cd
Apr 27 09:55:27 *REDACTED* nextdns[2324]: github.com/nextdns/nextdns/resolver/endpoint.(*activeEnpoint).do(0xc0097b3080, 0xc000323aa0, 0x0, 0x0)
Apr 27 09:55:27 *REDACTED* nextdns[2324]:         github.com/nextdns/nextdns/resolver/endpoint/manager.go:315 +0x5b
Apr 27 09:55:27 *REDACTED* nextdns[2324]: github.com/nextdns/nextdns/resolver/endpoint.(*Manager).Do(0xc0000a2c80, 0x56533e01ee20, 0xc0099c9560, 0xc000323aa0, 0x10, 0xc0003a7610)
Apr 27 09:55:27 *REDACTED* nextdns[2324]:         github.com/nextdns/nextdns/resolver/endpoint/manager.go:235 +0x5d
Apr 27 09:55:27 *REDACTED* nextdns[2324]: github.com/nextdns/nextdns/resolver.(*DNS).Resolve(0xc0000ce240, 0x56533e01ee20, 0xc0099c9560, 0x10001f52d, 0xc0003c4c20, 0xf, 0xc00069e168, 0x4, 0x4, 0x0, ...)
Apr 27 09:55:27 *REDACTED* nextdns[2324]:         github.com/nextdns/nextdns/resolver/resolver.go:73 +0x13c
Apr 27 09:55:27 *REDACTED* nextdns[2324]: github.com/nextdns/nextdns/proxy.Proxy.Resolve(0xc0000246e7, 0xc, 0x56533e0176c0, 0xc0000ce240, 0x101, 0x3b9aca00, 0xc00000e520, 0xc00000e540, 0xc00000e560, 0x56533e01ee20, ...)
Apr 27 09:55:27 *REDACTED* nextdns[2324]:         github.com/nextdns/nextdns/proxy/proxy.go:155 +0x19d
Apr 27 09:55:27 *REDACTED* nextdns[2324]: github.com/nextdns/nextdns/proxy.Proxy.serveUDP.func2(0xc00021faa0, 0x20, 0xc0002554a0, 0xc0000246e7, 0xc, 0x56533e0176c0, 0xc0000ce240, 0x101, 0x3b9aca00, 0xc00000e520, ...)
Apr 27 09:55:27 *REDACTED* nextdns[2324]:         github.com/nextdns/nextdns/proxy/udp.go:102 +0x42c
Apr 27 09:55:27 *REDACTED* nextdns[2324]: created by github.com/nextdns/nextdns/proxy.Proxy.serveUDP
Apr 27 09:55:27 *REDACTED* nextdns[2324]:         github.com/nextdns/nextdns/proxy/udp.go:71 +0x2d6
Apr 27 09:55:27 *REDACTED* systemd[1]: nextdns.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 27 09:55:27 *REDACTED* systemd[1]: nextdns.service: Failed with result 'exit-code'.
```
Any ideas, my Go knowledge is basic, feel free to do some finger pointing to obviously obvious.
Love the service, It drops ~20% of ad/spy traffic across my devices. Internet is not the same.

**Comment by rs** [comment]
Please upgrade to last version.

**Comment by inoperable** [comment]
This happens on `nextdns version 1.5.3` - so do you mean I should build from origin/master instead?
