### ISSUE TITLE
OpenWRT - Caching not working after upgrade to 1.6.3

### ISSUE THREAD

**Issue by varkey** [nextdns/nextdns#238]
I had enabled caching as per https://github.com/nextdns/nextdns/wiki/Cache-Configuration, and it was working fine (except for #230). I upgraded to `1.6.3` today using `opkg upgrade nextdns` and since then caching isn't working. (The upgrade itself was crazy, as it overwrote all my settings and set it up as new. I had to redo everything)

```
root@bumblebee:~# nextdns version
nextdns version 1.6.3
root@bumblebee:~# nextdns config
listen :53
cache-max-age 0s
use-hosts true
cache-size 10MB
detect-captive-portals false
hardened-privacy false
bogus-priv true
timeout 5s
auto-activate false
config <id>
log-queries false
max-ttl 0s
setup-router true
control /var/run/nextdns.sock
report-client-info true
root@bumblebee:~# nextdns cache-stats
null
root@bumblebee:~# nextdns cache-keys
null
root@bumblebee:~#
```
```
root@bumblebee:~# dig nextdns.io

; <<>> DiG 9.14.8 <<>> nextdns.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 30389
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1220
;; QUESTION SECTION:
;nextdns.io.			IN	A

;; ANSWER SECTION:
nextdns.io.		300	IN	A	172.67.183.218
nextdns.io.		300	IN	A	104.31.89.168
nextdns.io.		300	IN	A	104.31.88.168

;; Query time: 34 msec
;; SERVER: ::1#53(::1)
;; WHEN: Fri May 29 19:41:42 IST 2020
;; MSG SIZE  rcvd: 87

root@bumblebee:~# dig nextdns.io

; <<>> DiG 9.14.8 <<>> nextdns.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 61494
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1220
;; QUESTION SECTION:
;nextdns.io.			IN	A

;; ANSWER SECTION:
nextdns.io.		300	IN	A	172.67.183.218
nextdns.io.		300	IN	A	104.31.89.168
nextdns.io.		300	IN	A	104.31.88.168

;; Query time: 34 msec
;; SERVER: ::1#53(::1)
;; WHEN: Fri May 29 19:41:43 IST 2020
;; MSG SIZE  rcvd: 87

root@bumblebee:~#
```

**Context**
 - Version [e.g. 1.5.2]:  1.6.3
 - Platform [e.g. macOS, ASUS-Merlin]: OpenWRT x86_64

**Comment by varkey** [comment]
And the funny thing is, I went back to the `v1.5.8-SNAPSHOT-2ebe526` binary and even that is not caching now. Not sure what went wrong, did I miss some config?

**Comment by rs** [comment]
What do you get for `dig chaos test.com` from a LAN host?

**Comment by varkey** [comment]
```
;; Warning: Message parser reports malformed message packet.

; <<>> DiG 9.10.6 <<>> chaos test.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 20265
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 11

;; QUESTION SECTION:
;test.com.			CH	A

;; ANSWER SECTION:
test.com.		300	IN	A	0.0.0.0

;; ADDITIONAL SECTION:
server.nextdns.io.	0	CH	TXT	"gc-bom-1"
conf.nextdns.io.	0	CH	TXT	"fp6eefe94f6xxxxx"
device-ip.nextdns.io.	0	CH	TXT	"192.168.1.163"
device-model.nextdns.io. 0	CH	TXT	"mac:f0:18:98"
proto.nextdns.io.	0	CH	TXT	"DOH"
client.nextdns.io.	0	CH	TXT	"117.201.x.x"
client-name.nextdns.io.	0	CH	TXT	"nextdns-cli"
device-name.nextdns.io.	0	CH	TXT	"<name>"
device-id.nextdns.io.	0	CH	TXT	"EJN8L"
lists.nextdns.io.	0	CH	TXT	"blocklist:nextdns-recommended"
smart-ecs.nextdns.io.	0	CH	TXT	"not sent"

;; Query time: 59 msec
;; SERVER: 192.168.1.3#53(192.168.1.3)
;; WHEN: Sat May 30 08:26:39 IST 2020
;; MSG SIZE  rcvd: 421
```

**Comment by rs** [comment]
What do you get for `sudo nextdns log | grep Starting`

**Comment by varkey** [comment]
```
root@bumblebee:~# nextdns log | grep Starting
2020 May 30 00:41:44 bumblebee err nextdns[21576]: INFO: 00:41:44 Starting NextDNS 1.6.3/linux on 127.0.0.1:53
2020 May 30 00:43:28 bumblebee err nextdns[24632]: INFO: 00:43:28 Starting NextDNS 1.6.3/linux on :53
2020 May 30 00:43:28 bumblebee err nextdns[24632]: INFO: 00:43:28 Starting mDNS discovery
2020 May 30 00:45:32 bumblebee err nextdns[28225]: INFO: 00:45:32 Starting NextDNS 1.6.3/linux on :53
2020 May 30 00:45:32 bumblebee err nextdns[28225]: INFO: 00:45:32 Starting mDNS discovery
2020 May 30 08:26:21 bumblebee err nextdns[31370]: INFO: 08:26:21 Starting NextDNS 1.6.3/linux on :53
2020 May 30 08:26:21 bumblebee err nextdns[31370]: INFO: 08:26:21 Starting mDNS discovery
root@bumblebee:~#
```

**Comment by rs** [comment]
Can you please run `nextdns install`?

**Comment by varkey** [comment]
Wow, that did it. After that, it appears to be caching. What happened exactly? 🤔 

```
root@bumblebee:~# nextdns install
NextDNS installed and started using procd init
root@bumblebee:~#
```

```
2020 May 30 09:03:10 bumblebee err nextdns[31370]: INFO: 09:03:10 Stopping NextDNS 1.6.3/linux
2020 May 30 09:03:10 bumblebee err nextdns[31370]: INFO: 09:03:10 NextDNS 1.6.3/linux stopped
2020 May 30 09:03:11 bumblebee notice nextdns[27554]: Starting NextDNS 1.6.3/linux on :53
2020 May 30 09:03:11 bumblebee notice nextdns[27554]: Starting mDNS discovery
2020 May 30 09:03:11 bumblebee notice nextdns[27554]: Listening on UDP/:53
2020 May 30 09:03:11 bumblebee notice nextdns[27554]: Listening on TCP/:53
2020 May 30 09:03:12 bumblebee notice nextdns[27554]: Connected 45.90.28.0:443 (con=59ms tls=123ms, TLS13)
2020 May 30 09:03:14 bumblebee notice nextdns[27554]: Connected 34.93.164.22:443 (con=36ms tls=50ms, TLS13)
2020 May 30 09:03:14 bumblebee notice nextdns[27554]: Switching endpoint: https://gc-bom-1.edge.nextdns.io#34.93.164.22
2020 May 30 09:03:16 bumblebee notice nextdns[27554]: Activating
2020 May 30 09:04:13 bumblebee notice nextdns[27554]: Control client connected: &{{0xc0001ba580}}
2020 May 30 09:04:13 bumblebee notice nextdns[27554]: Control client disconnected: &{{0xc0001ba580}}
2020 May 30 09:04:19 bumblebee notice nextdns[27554]: Control client connected: &{{0xc0001bcf80}}
2020 May 30 09:04:19 bumblebee notice nextdns[27554]: Control client disconnected: &{{0xc0001bcf80}}
2020 May 30 09:04:21 bumblebee notice nextdns[27554]: Control client connected: &{{0xc0001bd100}}
2020 May 30 09:04:21 bumblebee notice nextdns[27554]: Control client disconnected: &{{0xc0001bd100}}
2020 May 30 09:04:49 bumblebee notice nextdns[27554]: Control client connected: &{{0xc00015cb80}}
2020 May 30 09:04:49 bumblebee notice nextdns[27554]: Control client disconnected: &{{0xc00015cb80}}
root@bumblebee:~# nextdns cache-stats
{
    "hit": 120,
    "miss": 85
}
```

**Comment by varkey** [comment]
I noticed that after running `nextdns install`, the init script at `/etc/init.d/nextdns` changed.

**Comment by rs** [comment]
The opkg does not run `nextdns install`, so you get the original init script which is not working correctly. I have a fix I need to test and submit.

**Comment by mad-it** [comment]
I also ran into this issue. This fixed my caching as wel but broke 1 thing, namely the log.
When I run `kill -QUIT <pid>` the logs outputed by `nextdns log` are truncated. 

Example of truncated logs:
```
Sat May 30 10:36:06 2020 daemon.notice nextdns[3553]: goroutine 1 [running]: github.com/nextdns/nextdns/host/service.runService(0x3bd198, 0x7, 0x451850, 0x2476000, 0x241aa01, 0x240e940)       github.com/nextdns/nextdns/host/service/run_unix.go:29 +0x1e0 github.com/nextdns/nextdns/host/service.Run(0x3bd198, 0x7, 0x451850, 0x2476000, 0x5, 0x2410548)    github.com/nextdns/nextdns/host/service/run.go:19 +0x98 main.run(0x24a6018, 0x1, 0x1, 0x0, 0x0)  github.com/nextdns/nextdns/run.go:366 +0x8f0 main.main()        github.com/nextdns/nextdns/main.go:69 +0x148  goroutine 77 [chan receive, 6 minutes]: github.com/nextdns/nextdns/discovery.(*MDNS).Start.func1(0x2510120, 0x24ab580, 0xe, 0x10, 0x451fd0, 0x249d340)     github.com/nextdns/nextdns/discovery/mdns.go:98 +0x24c created by github.com/nextdns/nextdns/discovery.(*MDNS).Start    github.com/nextdns/nextdns/discovery/mdns.go:76 +0x194  goroutine 75 [IO wait]: internal/poll.runtime_pollWait(0xa6b547bc, 0x72, 0x0)    runtime/netpoll.go:203 +0x44 internal/poll.(*pollDesc).wait(0x24c66a4, 0x72, 0x10000, 0x10
root@OpenWrt:~#
```

I do have to say, the logs worked fine before running `nextdns install`.
