### ISSUE TITLE
Runtime error: Invalid memory address or nil pointer deference

### ISSUE THREAD

**Issue by dashsd** [nextdns/nextdns#313]
After updating nextdns to version 1.8.1, it throws the following runtime error:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x5be640]

goroutine 1 [running]:
github.com/nextdns/nextdns/host/service/ubios.New(0x84c709, 0x7, 0x84e817, 0xd, 0x854fc5, 0x1b, 0xc00005eee0, 0x1, 0x1, 0x0, ...)
	/home/runner/work/nextdns/nextdns/host/service/ubios/service.go:26 +0x80
github.com/nextdns/nextdns/host.NewService(0x84c709, 0x7, 0x84e817, 0xd, 0x854fc5, 0x1b, 0xc00005eee0, 0x1, 0x1, 0xc00007cd88, ...)
	/home/runner/work/nextdns/nextdns/host/service_linux.go:18 +0xb8
main.svc(0xc00000c090, 0x1, 0x1, 0xc00007ce01, 0xc00005eed0)
	/home/runner/work/nextdns/nextdns/service.go:24 +0x205
main.main()
	/home/runner/work/nextdns/nextdns/main.go:70 +0x1a7

 - Version: 1.8.1
 - Platform: Ubuntu 20.04 (5.4.0-47), Fedora 32 (5.8.6-201)

**Comment by dashsd** [comment]
The issue got resolved after upgrading to version 1.8.2. The latest update was not showing up in the repositories. So, I had to refresh the repos to upgrade to the latest version on both Ubuntu and Fedora.
