### ISSUE TITLE
Set config via cli on OpenWRT get error

### ISSUE THREAD

**Issue by jamestombs** [nextdns/nextdns#451]
&lt;Describe the bug> Entering the following command via CLI:

`# nextdns config set -config 00:00:00:ff:ff:ff=YYYYY -config XXXXXX`

As per the documentation results in the following error:

```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/nextdns/nextdns/config.(*Config).Parse(0x818340, 0x818148, 0x5, 0x7)
        github.com/nextdns/nextdns@/config/config.go:73 +0x52c
main.svc(0x43041c, 0x6, 0x6, 0x1)
        github.com/nextdns/nextdns@/service.go:108 +0xb4
main.main()
        github.com/nextdns/nextdns@/main.go:64 +0x1c4
```
Even a simple command like `# nextdns config set -config XXXX` fails with same error.

**Context**
 - Version [e.g. 1.5.2]: 1.3.1
 - Platform [e.g. macOS, ASUS-Merlin]: OpenWRT

**Comment by rs** [comment]
Can you please upgrade to the last version and try again? 1.3.1 is very old.

**Comment by jamestombs** [comment]
OK, something not right. I only installed nextdns cli about 2 weeks ago. So it must have installed an old version using the bash script.

Now if I run the bash script, it says there's an update available, I choose the upgrade, it downloads various packages then prompts me with the same menu again asking if I want to upgrade.

```
root@OpenWrt:~# sh -c 'sh -c "$(curl -sL https://nextdns.io/install)"'
INFO: OS: openwrt
INFO: GOARCH: armv7
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /usr/sbin/nextdns
INFO: LATEST_RELEASE: 1.11.0
u) Upgrade NextDNS from 1.3.1 to 1.11.0
c) Configure NextDNS
r) Remove NextDNS
e) Exit
Choice (default=u): u
INFO: Upgrading NextDNS...
Downloading https://dc502wrt.org/snapshots/r11962/targets/mvebu/cortexa9/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_core
Downloading https://dc502wrt.org/snapshots/r11962/targets/mvebu/cortexa9/packages/Packages.sig
Signature check passed.
Downloading https://dc502wrt.org/snapshots/r11962/packages/arm_cortex-a9_vfpv3/base/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_base
Downloading https://dc502wrt.org/snapshots/r11962/packages/arm_cortex-a9_vfpv3/base/Packages.sig
Signature check passed.
Downloading https://dc502wrt.org/snapshots/r11962/packages/arm_cortex-a9_vfpv3/darkmatter/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_darkmatter
Downloading https://dc502wrt.org/snapshots/r11962/packages/arm_cortex-a9_vfpv3/darkmatter/Packages.sig
Signature check passed.
Downloading https://dc502wrt.org/snapshots/r11962/packages/arm_cortex-a9_vfpv3/luci/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_luci
Downloading https://dc502wrt.org/snapshots/r11962/packages/arm_cortex-a9_vfpv3/luci/Packages.sig
Signature check passed.
Downloading https://dc502wrt.org/snapshots/r11962/packages/arm_cortex-a9_vfpv3/opentomato/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_opentomato
Downloading https://dc502wrt.org/snapshots/r11962/packages/arm_cortex-a9_vfpv3/opentomato/Packages.sig
Signature check passed.
Downloading https://dc502wrt.org/snapshots/r11962/packages/arm_cortex-a9_vfpv3/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_packages
Downloading https://dc502wrt.org/snapshots/r11962/packages/arm_cortex-a9_vfpv3/packages/Packages.sig
Signature check passed.
Downloading https://dc502wrt.org/snapshots/r11962/packages/arm_cortex-a9_vfpv3/routing/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_routing
Downloading https://dc502wrt.org/snapshots/r11962/packages/arm_cortex-a9_vfpv3/routing/Packages.sig
Signature check passed.
Downloading https://dc502wrt.org/snapshots/r11962/packages/arm_cortex-a9_vfpv3/telephony/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_telephony
Downloading https://dc502wrt.org/snapshots/r11962/packages/arm_cortex-a9_vfpv3/telephony/Packages.sig
Signature check passed.
u) Upgrade NextDNS from 1.3.1 to 1.11.0
c) Configure NextDNS
r) Remove NextDNS
e) Exit
```

Looking through the install script, it should do `opkg upgrade nextdns` which doesn't output anything.

If running `opkg install nextdns`. I get:

```
root@OpenWrt:~# opkg install nextdns
Package nextdns (1.3.1-4) installed in root is up to date.
```

Is it possibly due to an old version of OpenWrt?

**Comment by rs** [comment]
Which version of openwrt di you have?

**Comment by jamestombs** [comment]
It's a snapshot, can't remember how old it is, OpenWrt SNAPSHOT r11962.

Just upgraded to latest stable OpenWrt which is showing as r11306, however this is getting the latest version of NextDNS. And I can see that LuCI is updated from v20 to v21.

So if anyone is unable to get latest version of NextDNS, update OpenWrt with the latest sysupgrade.bin file.
