### ISSUE TITLE
Problem with intermittent disconets on Android 11 devices (probably because of MAC changing on wifi interface)

### ISSUE THREAD

**Issue by Mile-Lile** [nextdns/nextdns#610]
**Context**
 - CLI Version: 0.0.0-SNAPSHOT-18416fa
 - Platform: 4.4.290 #4420 SMP Fri Nov 5 06:10:11 +07 2021 armv7l DD-WRT

I am testing whole this week nextdns cli on ddwrt, and I fouded some issues... I have problem that some clients (lan hosts) reports "no internet connection" although ping to google works... So I assumed it was ns resolution problem... but at the same time internet and nslookup works on other clients... all hosts are on the same "my first configuration" Problematic clients are Android 11 devices... all of them had this MAC changing option enabled by default on wifi interface... as soon as I disable this option everythink starts to work. look at the screenshot below:

![Screenshot_2021-11-12-20-19-54-371](https://user-images.githubusercontent.com/12752816/141528707-238e55dc-c23b-4672-a333-a0399a9b13b4.jpeg)

also happens on some linux devices that don't bind MAC with IP... but linux reports "duplicate IP" and when I enter static DHCP lease everything starts to work.... don't see connection of DHCP server and DNS but I just tell you my findings...

on my.nexrdns.io I see same hostnames entered twice:

![Screenshot_select-area_20211112211616](https://user-images.githubusercontent.com/12752816/141529328-e8a29e0e-c8fe-4bec-b001-ce7ea729df98.png)

here are some info that I collected if it can help:

``` root@mile-lile:~# /jffs/nextdns/nextdns trace
goroutine 31763 [running]:
main.run.func4({0x0, 0x0})
        /home/runner/work/nextdns/nextdns/run.go:177 +0x4c
github.com/nextdns/nextdns/ctl.(*Server).handle(0x8b4580, {0x40f340, 0xac2238}, {{0x818cf0, 0x5}, {0x0, 0x0}, 0x0})
        /home/runner/work/nextdns/nextdns/ctl/server.go:125 +0xc8
github.com/nextdns/nextdns/ctl.(*Server).handleEvents(0x8b4580, {0x40f340, 0xac2238})
        /home/runner/work/nextdns/nextdns/ctl/server.go:114 +0x124
created by github.com/nextdns/nextdns/ctl.(*Server).run
        /home/runner/work/nextdns/nextdns/ctl/server.go:85 +0x90

goroutine 1 [chan receive]:
github.com/nextdns/nextdns/host/service.runService({0x38b367, 0x7}, {0x40c400, 0x8da400})
        /home/runner/work/nextdns/nextdns/host/service/run_unix.go:22 +0xa0
github.com/nextdns/nextdns/host/service.Run({0x38b367, 0x7}, {0x40c400, 0x8da400})
        /home/runner/work/nextdns/nextdns/host/service/run.go:19 +0xa0
main.run({0x8ae018, 0x1, 0x1})
        /home/runner/work/nextdns/nextdns/run.go:387 +0x222c
main.main()
        /home/runner/work/nextdns/nextdns/main.go:72 +0x13c

goroutine 22 [IO wait]:
internal/poll.runtime_pollWait(0x66c3ae40, 0x72)
        /opt/hostedtoolcache/go/1.17.3/x64/src/runtime/netpoll.go:234 +0xac
internal/poll.(*pollDesc).wait(0x8c0334, 0x72, 0x0)
        /opt/hostedtoolcache/go/1.17.3/x64/src/internal/poll/fd_poll_runtime.go:84 +0x30
internal/poll.(*pollDesc).waitRead(...)
        /opt/hostedtoolcache/go/1.17.3/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0x8c0320)
        /opt/hostedtoolcache/go/1.17.3/x64/src/internal/poll/fd_unix.go:402 +0x234
net.(*netFD).accept(0x8c0320)
        /opt/hostedtoolcache/go/1.17.3/x64/src/net/fd_unix.go:173 +0x20
net.(*UnixListener).accept(0x8a2e00)
        /opt/hostedtoolcache/go/1.17.3/x64/src/net/unixsock_posix.go:167 +0x20
net.(*UnixListener).Accept(0x8a2e00)
        /opt/hostedtoolcache/go/1.17.3/x64/src/net/unixsock.go:260 +0x30
github.com/nextdns/nextdns/ctl.(*Server).run(0x8b4580, {0x40c438, 0x8a2e00})
        /home/runner/work/nextdns/nextdns/ctl/server.go:80 +0x24
created by github.com/nextdns/nextdns/ctl.(*Server).Start
        /home/runner/work/nextdns/nextdns/ctl/server.go:52 +0xb8

goroutine 31 [syscall]:
os/signal.signal_recv()
        /opt/hostedtoolcache/go/1.17.3/x64/src/runtime/sigqueue.go:169 +0xf0
os/signal.loop()
        /opt/hostedtoolcache/go/1.17.3/x64/src/os/signal/signal_unix.go:24 +0x14
created by os/signal.Notify.func1.1
        /opt/hostedtoolcache/go/1.17.3/x64/src/os/signal/signal.go:151 +0x30

goroutine 33 [chan receive, 2278 minutes]:
github.com/nextdns/nextdns/proxy.Proxy.ListenAndServe({{0x8a0938, 0x1, 0x1}, {0x40c0c0, 0x8ae610}, {0x407b90, 0x8ba8a0}, {0x0, 0x0}, 0x1, ...}, ...)
        /home/runner/work/nextdns/nextdns/proxy/proxy.go:146 +0x464
main.(*proxySvc).start.func1(0x8a0a68, 0x8da400, 0x8a0a60, 0x896380)
        /home/runner/work/nextdns/nextdns/run.go:96 +0x1ac
created by main.(*proxySvc).start
        /home/runner/work/nextdns/nextdns/run.go:88 +0x90

goroutine 34 [IO wait]:
internal/poll.runtime_pollWait(0x66c3aed8, 0x72)
        /opt/hostedtoolcache/go/1.17.3/x64/src/runtime/netpoll.go:234 +0xac
internal/poll.(*pollDesc).wait(0x8c06f4, 0x72, 0x0)
        /opt/hostedtoolcache/go/1.17.3/x64/src/internal/poll/fd_poll_runtime.go:84 +0x30
internal/poll.(*pollDesc).waitRead(...)
        /opt/hostedtoolcache/go/1.17.3/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).ReadMsg(0x8c06e0, {0x99e000, 0xffff, 0xffff}, {0x930d80, 0x20, 0x20}, 0x0)
        /opt/hostedtoolcache/go/1.17.3/x64/src/internal/poll/fd_unix.go:250 +0x264
net.(*netFD).readMsg(0x8c06e0, {0x99e000, 0xffff, 0xffff}, {0x930d80, 0x20, 0x20}, 0x0)
        /opt/hostedtoolcache/go/1.17.3/x64/src/net/fd_posix.go:68 +0x58
net.(*UDPConn).readMsg(0x8a0b48, {0x99e000, 0xffff, 0xffff}, {0x930d80, 0x20, 0x20})
        /opt/hostedtoolcache/go/1.17.3/x64/src/net/udpsock_posix.go:62 +0x58
net.(*UDPConn).ReadMsgUDP(0x8a0b48, {0x99e000, 0xffff, 0xffff}, {0x930d80, 0x20, 0x20})
        /opt/hostedtoolcache/go/1.17.3/x64/src/net/udpsock.go:144 +0x58
github.com/nextdns/nextdns/proxy.readUDP(0x8a0b48, {0x99e000, 0xffff, 0xffff})
        /home/runner/work/nextdns/nextdns/proxy/udp.go:141 +0x70
github.com/nextdns/nextdns/proxy.Proxy.serveUDP({{0x8a0938, 0x1, 0x1}, {0x40c0c0, 0x8ae610}, {0x407b90, 0x8ba8a0}, {0x0, 0x0}, 0x1, ...}, ...)
        /home/runner/work/nextdns/nextdns/proxy/udp.go:63 +0x1cc
github.com/nextdns/nextdns/proxy.Proxy.ListenAndServe.func1({{0x8a0938, 0x1, 0x1}, {0x40c0c0, 0x8ae610}, {0x407b90, 0x8ba8a0}, {0x0, 0x0}, 0x1, ...}, ...)
        /home/runner/work/nextdns/nextdns/proxy/proxy.go:119 +0x244
created by github.com/nextdns/nextdns/proxy.Proxy.ListenAndServe
        /home/runner/work/nextdns/nextdns/proxy/proxy.go:111 +0x3b8

goroutine 35 [IO wait, 2278 minutes]:
internal/poll.runtime_pollWait(0x66c3ada8, 0x72)
        /opt/hostedtoolcache/go/1.17.3/x64/src/runtime/netpoll.go:234 +0xac
internal/poll.(*pollDesc).wait(0x8c06a4, 0x72, 0x0)
        /opt/hostedtoolcache/go/1.17.3/x64/src/internal/poll/fd_poll_runtime.go:84 +0x30
internal/poll.(*pollDesc).waitRead(...)
        /opt/hostedtoolcache/go/1.17.3/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0x8c0690)
        /opt/hostedtoolcache/go/1.17.3/x64/src/internal/poll/fd_unix.go:402 +0x234
net.(*netFD).accept(0x8c0690)
        /opt/hostedtoolcache/go/1.17.3/x64/src/net/fd_unix.go:173 +0x20
net.(*TCPListener).accept(0x8ae6b0)
        /opt/hostedtoolcache/go/1.17.3/x64/src/net/tcpsock_posix.go:140 +0x20
net.(*TCPListener).Accept(0x8ae6b0)
        /opt/hostedtoolcache/go/1.17.3/x64/src/net/tcpsock.go:262 +0x30
github.com/nextdns/nextdns/proxy.Proxy.serveTCP({{0x8a0938, 0x1, 0x1}, {0x40c0c0, 0x8ae610}, {0x407b90, 0x8ba8a0}, {0x0, 0x0}, 0x1, ...}, ...)
        /home/runner/work/nextdns/nextdns/proxy/tcp.go:29 +0x40
github.com/nextdns/nextdns/proxy.Proxy.ListenAndServe.func2({{0x8a0938, 0x1, 0x1}, {0x40c0c0, 0x8ae610}, {0x407b90, 0x8ba8a0}, {0x0, 0x0}, 0x1, ...}, ...)
        /home/runner/work/nextdns/nextdns/proxy/proxy.go:136 +0x244
created by github.com/nextdns/nextdns/proxy.Proxy.ListenAndServe
        /home/runner/work/nextdns/nextdns/proxy/proxy.go:128 +0x420

goroutine 31752 [IO wait]:
internal/poll.runtime_pollWait(0x66c3abe0, 0x72)
        /opt/hostedtoolcache/go/1.17.3/x64/src/runtime/netpoll.go:234 +0xac
internal/poll.(*pollDesc).wait(0x93ac94, 0x72, 0x0)
        /opt/hostedtoolcache/go/1.17.3/x64/src/internal/poll/fd_poll_runtime.go:84 +0x30
internal/poll.(*pollDesc).waitRead(...)
        /opt/hostedtoolcache/go/1.17.3/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0x93ac80, {0x91a000, 0x205, 0x205})
        /opt/hostedtoolcache/go/1.17.3/x64/src/internal/poll/fd_unix.go:167 +0x200
net.(*netFD).Read(0x93ac80, {0x91a000, 0x205, 0x205})
        /opt/hostedtoolcache/go/1.17.3/x64/src/net/fd_posix.go:56 +0x38
net.(*conn).Read(0xac2010, {0x91a000, 0x205, 0x205})
        /opt/hostedtoolcache/go/1.17.3/x64/src/net/net.go:183 +0x48
crypto/tls.(*atLeastReader).Read(0xb984a0, {0x91a000, 0x205, 0x205})
        /opt/hostedtoolcache/go/1.17.3/x64/src/crypto/tls/conn.go:777 +0x7c
bytes.(*Buffer).ReadFrom(0x97c36c, {0x407a64, 0xb984a0})
        /opt/hostedtoolcache/go/1.17.3/x64/src/bytes/buffer.go:204 +0xa4
crypto/tls.(*Conn).readFromUntil(0x97c200, {0x66bf9cf0, 0xd10010}, 0x5)
        /opt/hostedtoolcache/go/1.17.3/x64/src/crypto/tls/conn.go:799 +0xd4
crypto/tls.(*Conn).readRecordOrCCS(0x97c200, 0x0)
        /opt/hostedtoolcache/go/1.17.3/x64/src/crypto/tls/conn.go:606 +0x11c
crypto/tls.(*Conn).readRecord(...)
        /opt/hostedtoolcache/go/1.17.3/x64/src/crypto/tls/conn.go:574
crypto/tls.(*Conn).Read(0x97c200, {0x93c000, 0x1000, 0x1000})
        /opt/hostedtoolcache/go/1.17.3/x64/src/crypto/tls/conn.go:1277 +0x150
bufio.(*Reader).Read(0x9914a0, {0x8da1a0, 0x9, 0x9})
        /opt/hostedtoolcache/go/1.17.3/x64/src/bufio/bufio.go:227 +0x228
io.ReadAtLeast({0x4079c4, 0x9914a0}, {0x8da1a0, 0x9, 0x9}, 0x9)
        /opt/hostedtoolcache/go/1.17.3/x64/src/io/io.go:328 +0x90
io.ReadFull(...)
        /opt/hostedtoolcache/go/1.17.3/x64/src/io/io.go:347
net/http.http2readFrameHeader({0x8da1a0, 0x9, 0x9}, {0x4079c4, 0x9914a0})
        /opt/hostedtoolcache/go/1.17.3/x64/src/net/http/h2_bundle.go:1555 +0x54
net/http.(*http2Framer).ReadFrame(0x8da180)
        /opt/hostedtoolcache/go/1.17.3/x64/src/net/http/h2_bundle.go:1813 +0x90
net/http.(*http2clientConnReadLoop).run(0x861fd4)
        /opt/hostedtoolcache/go/1.17.3/x64/src/net/http/h2_bundle.go:8583 +0x13c
net/http.(*http2ClientConn).readLoop(0x9581e0)
        /opt/hostedtoolcache/go/1.17.3/x64/src/net/http/h2_bundle.go:8506 +0x54
created by net/http.(*http2Transport).newClientConn
        /opt/hostedtoolcache/go/1.17.3/x64/src/net/http/h2_bundle.go:7317 +0xb90

```
``` root@mile-lile:~# /jffs/nextdns/nextdns config
setup-router true
listen localhost:53
cache-size 0
max-ttl 0s
hardened-privacy false
bogus-priv true
use-hosts true
timeout 5s
control /var/run/nextdns.sock
log-queries false
cache-max-age 0s
max-inflight-requests 256
auto-activate false
config 39d5fc
report-client-info false
discovery-dns 
detect-captive-portals false```

and a lot of these OK log:

``` Nov 12 18:27:05 mile-lile daemon.notice nextdns[12706]: Connected 194.71.126.128:443 (con=9ms tls=24ms, TCP, TLS13)
Nov 12 18:29:45 mile-lile daemon.notice nextdns[12706]: Connected 194.71.126.128:443 (con=9ms tls=26ms, TCP, TLS13)
Nov 12 18:31:11 mile-lile daemon.notice nextdns[12706]: Connected 217.146.8.49:443 (con=8ms tls=25ms, TCP, TLS13)
Nov 12 18:33:30 mile-lile daemon.notice nextdns[12706]: Connected 217.146.8.49:443 (con=8ms tls=28ms, TCP, TLS13)
Nov 12 18:34:45 mile-lile daemon.notice nextdns[12706]: Connected 194.71.126.128:443 (con=8ms tls=24ms, TCP, TLS13)
Nov 12 18:36:09 mile-lile daemon.notice nextdns[12706]: Connected 194.71.126.128:443 (con=10ms tls=24ms, TCP, TLS13)
Nov 12 18:44:37 mile-lile daemon.notice nextdns[12706]: Connected 194.71.126.128:443 (con=12ms tls=27ms, TCP, TLS13)
Nov 12 18:46:15 mile-lile daemon.notice nextdns[12706]: Connected 194.71.126.128:443 (con=8ms tls=25ms, TCP, TLS13)
Nov 12 18:49:03 mile-lile daemon.notice nextdns[12706]: Connected 194.71.126.128:443 (con=10ms tls=24ms, TCP, TLS13)
Nov 12 18:50:13 mile-lile daemon.notice nextdns[12706]: Connected 217.146.8.49:443 (con=9ms tls=25ms, TCP, TLS13)
Nov 12 18:53:08 mile-lile daemon.notice nextdns[12706]: Connected 217.146.8.49:443 (con=9ms tls=23ms, TCP, TLS13)
Nov 12 18:54:37 mile-lile daemon.notice nextdns[12706]: Connected 194.71.126.128:443 (con=8ms tls=31ms, TCP, TLS13)
Nov 12 18:58:06 mile-lile daemon.notice nextdns[12706]: Connected 194.71.126.128:443 (con=8ms tls=26ms, TCP, TLS13)
Nov 12 19:01:21 mile-lile daemon.notice nextdns[12706]: Connected 194.71.126.128:443 (con=9ms tls=23ms, TCP, TLS13)
Nov 12 19:03:39 mile-lile daemon.notice nextdns[12706]: Connected 194.71.126.128:443 (con=8ms tls=24ms, TCP, TLS13)
Nov 12 19:13:32 mile-lile daemon.notice nextdns[12706]: Connected 217.146.8.49:443 (con=18ms tls=35ms, TCP, TLS13)
Nov 12 19:16:22 mile-lile daemon.notice nextdns[12706]: Connected 194.71.126.128:443 (con=9ms tls=28ms, TCP, TLS13)
Nov 12 19:20:24 mile-lile daemon.notice nextdns[12706]: Connected 194.71.126.128:443 (con=8ms tls=30ms, TCP, TLS13)
Nov 12 19:23:33 mile-lile daemon.notice nextdns[12706]: Connected 194.71.126.128:443 (con=15ms tls=32ms, TCP, TLS13)
Nov 12 19:26:28 mile-lile daemon.notice nextdns[12706]: Connected 194.71.126.128:443 (con=8ms tls=33ms, TCP, TLS13)
Nov 12 19:29:16 mile-lile daemon.notice nextdns[12706]: Connected 194.71.126.128:443 (con=11ms tls=25ms, TCP, TLS13)
Nov 12 19:30:20 mile-lile daemon.notice nextdns[12706]: Connected 217.146.8.49:443 (con=16ms tls=24ms, TCP, TLS13)
Nov 12 19:31:20 mile-lile daemon.notice nextdns[12706]: Connected 194.71.126.128:443 (con=8ms tls=23ms, TCP, TLS13)
Nov 12 19:32:39 mile-lile daemon.notice nextdns[12706]: Connected 194.71.126.128:443 (con=11ms tls=26ms, TCP, TLS13)
Nov 12 19:33:40 mile-lile daemon.notice nextdns[12706]: Connected 194.71.126.128:443 (con=11ms tls=27ms, TCP, TLS13)
Nov 12 19:34:16 mile-lile daemon.notice nextdns[12706]: Connected 194.71.126.128:443 (con=10ms tls=23ms, TCP, TLS13)
Nov 12 19:35:41 mile-lile daemon.notice nextdns[12706]: Connected 194.71.126.128:443 (con=14ms tls=23ms, TCP, TLS13)
Nov 12 19:38:41 mile-lile daemon.notice nextdns[12706]: Connected 194.71.126.128:443 (con=13ms tls=29ms, TCP, TLS13)
Nov 12 19:39:41 mile-lile daemon.notice nextdns[12706]: Connected 194.71.126.128:443 (con=10ms tls=25ms, TCP, TLS13)
Nov 12 19:40:41 mile-lile daemon.notice nextdns[12706]: Connected 217.146.8.49:443 (con=9ms tls=25ms, TCP, TLS13)
Nov 12 19:42:15 mile-lile daemon.notice nextdns[12706]: Connected 194.71.126.128:443 (con=10ms tls=24ms, TCP, TLS13)
Nov 12 19:45:06 mile-lile daemon.notice nextdns[12706]: Connected 194.71.126.128:443 (con=9ms tls=25ms, TCP, TLS13)
Nov 12 19:46:26 mile-lile daemon.notice nextdns[12706]: Connected 194.71.126.128:443 (con=10ms tls=25ms, TCP, TLS13)
Nov 12 19:48:55 mile-lile daemon.notice nextdns[12706]: Connected 194.71.126.128:443 (con=8ms tls=24ms, TCP, TLS13)
Nov 12 19:49:53 mile-lile daemon.notice nextdns[12706]: Connected 194.71.126.128:443 (con=11ms tls=23ms, TCP, TLS13)
Nov 12 19:52:10 mile-lile daemon.notice nextdns[12706]: Connected 194.71.126.128:443 (con=5ms tls=25ms, TCP, TLS13)
Nov 12 19:54:00 mile-lile daemon.notice nextdns[12706]: Connected 194.71.126.128:443 (con=10ms tls=26ms, TCP, TLS13)
Nov 12 19:54:50 mile-lile daemon.notice nextdns[12706]: Connected 194.71.126.128:443 (con=10ms tls=24ms, TCP, TLS13)
Nov 12 19:57:37 mile-lile daemon.notice nextdns[12706]: Connected 194.71.126.128:443 (con=11ms tls=23ms, TCP, TLS13)
Nov 12 20:00:12 mile-lile daemon.notice nextdns[12706]: Connected 194.71.126.128:443 (con=10ms tls=31ms, TCP, TLS13)
Nov 12 20:00:46 mile-lile daemon.notice nextdns[12706]: Connected 194.71.126.128:443 (con=10ms tls=24ms, TCP, TLS13)
Nov 12 20:01:23 mile-lile daemon.notice nextdns[12706]: Connected 194.71.126.128:443 (con=11ms tls=26ms, TCP, TLS13)
Nov 12 20:02:40 mile-lile daemon.notice nextdns[12706]: Connected 194.71.126.128:443 (con=19ms tls=28ms, TCP, TLS13)
Nov 12 20:03:41 mile-lile daemon.notice nextdns[12706]: Connected 194.71.126.128:443 (con=10ms tls=33ms, TCP, TLS13)
Nov 12 20:05:59 mile-lile daemon.notice nextdns[12706]: Connected 194.71.126.128:443 (con=11ms tls=25ms, TCP, TLS13)
Nov 12 20:07:36 mile-lile daemon.notice nextdns[12706]: Connected 194.71.126.128:443 (con=0ms tls=0ms, TCP, )
Nov 12 20:08:35 mile-lile daemon.notice nextdns[12706]: Connected 194.71.126.128:443 (con=9ms tls=702ms, TCP, TLS13)
Nov 12 20:11:54 mile-lile daemon.notice nextdns[12706]: Connected 194.71.126.128:443 (con=13ms tls=27ms, TCP, TLS13)
Nov 12 20:12:49 mile-lile daemon.notice nextdns[12706]: Connected 194.71.126.128:443 (con=10ms tls=24ms, TCP, TLS13)
Nov 12 20:16:09 mile-lile daemon.notice nextdns[12706]: Connected 194.71.126.128:443 (con=9ms tls=27ms, TCP, TLS13)
Nov 12 20:17:22 mile-lile daemon.notice nextdns[12706]: Connected 194.71.126.128:443 (con=15ms tls=26ms, TCP, TLS13)
Nov 12 20:18:47 mile-lile daemon.notice nextdns[12706]: Connected 217.146.8.49:443 (con=15ms tls=29ms, TCP, TLS13)
Nov 12 20:23:05 mile-lile daemon.notice nextdns[12706]: Connected 194.71.126.128:443 (con=14ms tls=30ms, TCP, TLS13)
Nov 12 20:37:05 mile-lile daemon.notice nextdns[12706]: Connected 194.71.126.128:443 (con=18ms tls=36ms, TCP, TLS13)
Nov 12 20:38:09 mile-lile daemon.notice nextdns[12706]: Connected 217.146.8.49:443 (con=8ms tls=27ms, TCP, TLS13)
Nov 12 20:38:54 mile-lile daemon.notice nextdns[12706]: Connected 194.71.126.128:443 (con=11ms tls=31ms, TCP, TLS13)
Nov 12 20:39:56 mile-lile daemon.notice nextdns[12706]: Connected 194.71.126.128:443 (con=11ms tls=27ms, TCP, TLS13)
Nov 12 20:41:09 mile-lile daemon.notice nextdns[12706]: Connected 194.71.126.128:443 (con=8ms tls=27ms, TCP, TLS13)
Nov 12 20:43:32 mile-lile daemon.notice nextdns[12706]: Connected 194.71.126.128:443 (con=8ms tls=28ms, TCP, TLS13)
Nov 12 20:44:09 mile-lile daemon.notice nextdns[12706]: Connected 194.71.126.128:443 (con=13ms tls=27ms, TCP, TLS13)
Nov 12 20:44:59 mile-lile daemon.notice nextdns[12706]: Connected 217.146.8.49:443 (con=13ms tls=29ms, TCP, TLS13)
Nov 12 20:46:46 mile-lile daemon.notice nextdns[12706]: Connected 217.146.8.49:443 (con=20ms tls=33ms, TCP, TLS13)
Nov 12 20:47:40 mile-lile daemon.notice nextdns[12706]: Connected 194.71.126.128:443 (con=16ms tls=26ms, TCP, TLS13)
Nov 12 20:48:59 mile-lile daemon.notice nextdns[12706]: Connected 194.71.126.128:443 (con=11ms tls=23ms, TCP, TLS13)
Nov 12 20:50:08 mile-lile daemon.notice nextdns[12706]: Connected 194.71.126.128:443 (con=9ms tls=25ms, TCP, TLS13)
Nov 12 20:50:43 mile-lile daemon.notice nextdns[12706]: Connected 194.71.126.128:443 (con=9ms tls=29ms, TCP, TLS13)
Nov 12 20:51:41 mile-lile daemon.notice nextdns[12706]: Connected 194.71.126.128:443 (con=8ms tls=25ms, TCP, TLS13)
```

**Comment by Mile-Lile** [comment]
I uploaded  wrong config file... it doesn't work when using nextdns single (without dnsmasq)... then I must use static leases... this is config

```  root@mile-lile:~# /jffs/nextdns/nextdns config
cache-size 10MB
max-ttl 5s
bogus-priv true
auto-activate false
config 39d5fc
log-queries false
timeout 5s
setup-router true
report-client-info true
use-hosts true
cache-max-age 0s
discovery-dns 
detect-captive-portals false
max-inflight-requests 256
listen localhost:53
control /var/run/nextdns.sock
hardened-privacy false
```

I am willing to give access to my router so you can check what is wrong... let me know if you are interested...

**Comment by Mile-Lile** [comment]
the problem is same as for the people on openwrt [https://forum.openwrt.org/t/nextdns-on-openwrt-device-names-are-not-reported/61287/18](url)

**Comment by Mile-Lile** [comment]
ivalid
