### ISSUE TITLE
bogus-priv causes gethostbyaddr() to hang for 15s before erroring out

### ISSUE THREAD

**Issue by brainsik** [nextdns/nextdns#779]
**Context**
 - CLI Version: 1.38.0
 - Platform: pfSense 22.05-RELEASE (amd64) / FreeBSD 12.3-STABLE 

This is a follow-up to #750 which was opened to fix the problem where `gethostbyaddr()` will hang (and error out after 15s) for non-existent reverse lookups when `bogus-priv true` is set. Unfortunately, the problem persists, which can cause the DHCP Leases page on pfSense to time out (due to the 15s lookup per host without hostname set). 

## bogus-priv true

`gethostbyaddr()` hangs for 15s before erroring:

```
$ /usr/bin/time python3.8 -c 'import socket; socket.gethostbyaddr("10.19.47.50")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
socket.herror: [Errno 2] Host name lookup failure
       15.18 real         0.14 user         0.01 sys
```

```
$ dig -x 10.19.47.50

; <<>> DiG 9.16.26 <<>> -x 10.19.47.50
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 50706
;; flags: qr; QUERY: 0, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; Query time: 1 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Thu Jan 05 16:28:57 PST 2023
;; MSG SIZE  rcvd: 12
```

## bogus-priv false

`gethostbyaddr()` quickly returns Unknown host:

```
$ /usr/bin/time python3.8 -c 'import socket; socket.gethostbyaddr("10.19.47.50")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
socket.herror: [Errno 1] Unknown host
        0.16 real         0.11 user         0.04 sys
```

```
$ dig -x 10.19.47.50

; <<>> DiG 9.16.26 <<>> -x 10.19.47.50
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 47985
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;50.47.19.10.in-addr.arpa.	IN	PTR

;; AUTHORITY SECTION:
10.in-addr.arpa.	5	IN	SOA	prisoner.iana.org. hostmaster.root-servers.org. 1 604800 60 604800 604800

;; Query time: 15 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Thu Jan 05 16:30:40 PST 2023
;; MSG SIZE  rcvd: 130
```

**Comment by rcork** [comment]
Is this in 1.39.4? I don't see it listed in the release notes and my pfsense instance still times out on the DHCP leases page.

**Comment by brainsik** [comment]
AFAICT, it's still in master awaiting release.

As a work-around, I've configured nextdns to forward all private IPv4 reverse lookups to the local unbound instance, which gives a proper response. This fixes the issue with the DHCP Leases page hanging.

If you copy this, make sure to match it to whatever port you've got unbound listening on.

<details>

```
# workaround bogus-priv causing getaddrinfo() to hang
bogus-priv false
forwarder 10.in-addr.arpa.=127.0.0.1:10053
forwarder 16.172.in-addr.arpa.=127.0.0.1:10053
forwarder 17.172.in-addr.arpa.=127.0.0.1:10053
forwarder 18.172.in-addr.arpa.=127.0.0.1:10053
forwarder 19.172.in-addr.arpa.=127.0.0.1:10053
forwarder 20.172.in-addr.arpa.=127.0.0.1:10053
forwarder 21.172.in-addr.arpa.=127.0.0.1:10053
forwarder 22.172.in-addr.arpa.=127.0.0.1:10053
forwarder 23.172.in-addr.arpa.=127.0.0.1:10053
forwarder 24.172.in-addr.arpa.=127.0.0.1:10053
forwarder 25.172.in-addr.arpa.=127.0.0.1:10053
forwarder 26.172.in-addr.arpa.=127.0.0.1:10053
forwarder 27.172.in-addr.arpa.=127.0.0.1:10053
forwarder 28.172.in-addr.arpa.=127.0.0.1:10053
forwarder 29.172.in-addr.arpa.=127.0.0.1:10053
forwarder 30.172.in-addr.arpa.=127.0.0.1:10053
forwarder 31.172.in-addr.arpa.=127.0.0.1:10053
forwarder 168.192.in-addr.arpa.=127.0.0.1:10053
```

</details>

**Comment by rs** [comment]
You can try the master binary here: https://snapshot.nextdns.io/master/index.html
