### ISSUE TITLE
NextDNS CLI 1.38.0 stuck on "Setting up router" + "Activating"

### ISSUE THREAD

**Issue by KenKilty** [nextdns/nextdns#781]
**Context**
 - CLI Version: nextdns version 1.38.0
 - Platform: FreeBSD 13.1-RELEASE-p3 amd64 (also reproduceable on FreeBSD 13.1-RELEASE-p3 arm64)
 - IPv4/IPv6 enabled
 - Router mode w/auto activate enabled

Upon reboot of the system, nextdns client in router mode intermittently fails to activate as a router. The service starts but the router activation fails. Manually stopping the service, starting the service again sometimes resolves the issue but not always. Frequent reboots and the service will eventually activate. This problem can be reproduced on both x64 and armhf hardware platforms. 

Update: Temporary workaround (needed again after reboot): ```service netif restart```. A sledgehammer yes, I know. :-)

nextdns config:

```console
setup-router true
log-queries false
cache-max-age 0s
report-client-info true
detect-captive-portals false
hardened-privacy false
bogus-priv true
discovery-dns
mdns all
use-hosts true
timeout 5s
max-inflight-requests 256
listen localhost:53
control /var/run/nextdns.sock
config REDACTED
cache-size 10MB
max-ttl 5s
auto-activate true
```

Typical startup sequence when the nextdns service won't activate:

```console
Jan 12 08:48:43 nextdns nextdns[3130]: Connected [2a07:a8c0::]:443 (con=21ms tls=40ms, TCP, TLS13)
Jan 12 08:48:47 nextdns nextdns[3130]: Setting up router
Jan 12 08:48:47 nextdns nextdns[3130]: Activating
Jan 12 08:53:43 nextdns nextdns[3130]: Received signal: terminated
Jan 12 08:53:43 nextdns nextdns[3130]: Stopping NextDNS 1.38.0/freebsd
Jan 12 08:53:43 nextdns nextdns[3130]: Restore router settings
Jan 12 08:53:43 nextdns nextdns[3130]: Deactivating
Jan 12 08:53:43 nextdns nextdns[3130]: NextDNS 1.38.0/freebsd stopped
Jan 12 08:54:59 nextdns nextdns[3261]: Starting NextDNS 1.38.0/freebsd on :53
Jan 12 08:54:59 nextdns nextdns[3261]: Starting mDNS discovery
Jan 12 08:54:59 nextdns nextdns[3261]: Listening on TCP/:53
Jan 12 08:54:59 nextdns nextdns[3261]: Listening on UDP/:53
Jan 12 08:55:03 nextdns nextdns[3261]: Connected [2a07:a8c0::]:443 (con=15ms tls=40ms, TCP, TLS13)
Jan 12 08:55:03 nextdns nextdns[3261]: Connected [2620:11f:7000:1fe::]:443 (con=19ms tls=34ms, TCP, TLS13)
Jan 12 08:55:03 nextdns nextdns[3261]: Switching endpoint: https://dns.nextdns.io#104.244.209.134,74.118.138.167,2620:11f:7000:1fe::,2607:fdc0:5:9::24e
Jan 12 08:55:04 nextdns nextdns[3261]: Setting up router
Jan 12 08:55:04 nextdns nextdns[3261]: Activating
```

If nextdns is set to not auto-activate via the nextdns activate command will not work:

```console
sudo nextdns config set -auto-activate=false
sudo nextdns start
sudo nextdns log

Jan 12 09:08:25 nextdns nextdns[3504]: Switching endpoint: https://dns.nextdns.io#104.244.209.134,74.118.138.167,2620:11f:7000:1fe::,2607:fdc0:5:9::24e
Jan 12 09:08:29 nextdns nextdns[3504]: Setting up router

sudo nextdns activate
sudo nextdns log  <-- no change in status

Jan 12 09:08:25 nextdns nextdns[3504]: Switching endpoint: https://dns.nextdns.io#104.244.209.134,74.118.138.167,2620:11f:7000:1fe::,2607:fdc0:5:9::24e
Jan 12 09:08:29 nextdns nextdns[3504]: Setting up router
```

Typical nextdns stacktrace when stuck activating:

```console
nextdns@nextdns:~ $ sudo nextdns trace
goroutine 1219 [running]:
main.run.func5({0x771bc0?, 0x84c08d0e0?})
        /home/runner/work/nextdns/nextdns/run.go:177 +0x3f
github.com/nextdns/nextdns/ctl.(*Server).handle(0x84c116000, {0x86ca58, 0x84c0a4030}, {{0x84c245a08, 0x5}, {0x0, 0x0}, 0x0})
        /home/runner/work/nextdns/nextdns/ctl/server.go:125 +0x14d
github.com/nextdns/nextdns/ctl.(*Server).handleEvents(0x84c116000, {0x86ca58?, 0x84c0a4030})
        /home/runner/work/nextdns/nextdns/ctl/server.go:114 +0x169
created by github.com/nextdns/nextdns/ctl.(*Server).run
        /home/runner/work/nextdns/nextdns/ctl/server.go:85 +0xd8

goroutine 1 [chan receive]:
github.com/nextdns/nextdns/host/service.runService({0x7d038e?, 0x10?}, {0x86a3b0, 0x84c114000})
        /home/runner/work/nextdns/nextdns/host/service/run_unix.go:22 +0x85
github.com/nextdns/nextdns/host/service.Run({0x7cd39d, 0x7}, {0x86a3b0, 0x84c114000})
        /home/runner/work/nextdns/nextdns/host/service/run.go:19 +0x8b
main.run({0x84c0ac010, 0x1, 0x1})
        /home/runner/work/nextdns/nextdns/run.go:391 +0x1f65
main.main()
        /home/runner/work/nextdns/nextdns/main.go:72 +0x151

goroutine 18 [IO wait]:
internal/poll.runtime_pollWait(0x8539647d0, 0x72)
        /opt/hostedtoolcache/go/1.19.1/x64/src/runtime/netpoll.go:305 +0x89
internal/poll.(*pollDesc).wait(0x84c098380?, 0x18?, 0x0)
        /opt/hostedtoolcache/go/1.19.1/x64/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
        /opt/hostedtoolcache/go/1.19.1/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0x84c098380)
        /opt/hostedtoolcache/go/1.19.1/x64/src/internal/poll/fd_unix.go:614 +0x234
net.(*netFD).accept(0x84c098380)
        /opt/hostedtoolcache/go/1.19.1/x64/src/net/fd_unix.go:172 +0x35
net.(*UnixListener).accept(0x43f940?)
        /opt/hostedtoolcache/go/1.19.1/x64/src/net/unixsock_posix.go:166 +0x1c
net.(*UnixListener).Accept(0x84c08d0b0)
        /opt/hostedtoolcache/go/1.19.1/x64/src/net/unixsock.go:260 +0x3d
github.com/nextdns/nextdns/ctl.(*Server).run(0x84c116000, {0x86a410, 0x84c08d0b0})
        /home/runner/work/nextdns/nextdns/ctl/server.go:80 +0x3c
created by github.com/nextdns/nextdns/ctl.(*Server).Start
        /home/runner/work/nextdns/nextdns/ctl/server.go:52 +0xea

goroutine 19 [syscall]:
os/signal.signal_recv()
        /opt/hostedtoolcache/go/1.19.1/x64/src/runtime/sigqueue.go:152 +0x2f
os/signal.loop()
        /opt/hostedtoolcache/go/1.19.1/x64/src/os/signal/signal_unix.go:23 +0x19
created by os/signal.Notify.func1.1
        /opt/hostedtoolcache/go/1.19.1/x64/src/os/signal/signal.go:151 +0x2a

goroutine 5 [chan receive, 8 minutes]:
github.com/nextdns/nextdns/proxy.Proxy.ListenAndServe({{0x84c08b130, 0x1, 0x1}, {0x869e78, 0x84c094390}, {0x867ba0, 0x84c1122d0}, {0x869e78, 0x84c0943d8}, 0x1, ...}, ...)
        /home/runner/work/nextdns/nextdns/proxy/proxy.go:147 +0x205
main.(*proxySvc).start.func1()
        /home/runner/work/nextdns/nextdns/run.go:96 +0x2d8
created by main.(*proxySvc).start
        /home/runner/work/nextdns/nextdns/run.go:88 +0xef

goroutine 7 [IO wait]:
internal/poll.runtime_pollWait(0x853964500, 0x72)
        /opt/hostedtoolcache/go/1.19.1/x64/src/runtime/netpoll.go:305 +0x89
internal/poll.(*pollDesc).wait(0x84c024180?, 0x84c2ee000?, 0x0)
        /opt/hostedtoolcache/go/1.19.1/x64/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
        /opt/hostedtoolcache/go/1.19.1/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).ReadMsgInet6(0x84c024180, {0x84c2ee000, 0xffff, 0xffff}, {0x84c15de60, 0x60, 0x60}, 0x417273?, 0x2000?)
        /opt/hostedtoolcache/go/1.19.1/x64/src/internal/poll/fd_unix.go:358 +0x2dd
net.(*netFD).readMsgInet6(0x84c024180, {0x84c2ee000?, 0x84c0940a8?, 0x0?}, {0x84c15de60?, 0x8?, 0x821fea5b8?}, 0x18?, 0x84c044400?)
        /opt/hostedtoolcache/go/1.19.1/x64/src/net/fd_posix.go:90 +0x37
net.(*UDPConn).readMsg(0x44b6f2?, {0x84c2ee000?, 0x75adc0?, 0x14?}, {0x84c15de60?, 0x8?, 0x60?})
        /opt/hostedtoolcache/go/1.19.1/x64/src/net/udpsock_posix.go:106 +0xa5
net.(*UDPConn).ReadMsgUDPAddrPort(0x84c012028, {0x84c2ee000?, 0x60?, 0x84c044400?}, {0x84c15de60?, 0x0?, 0x84c084d90?})
        /opt/hostedtoolcache/go/1.19.1/x64/src/net/udpsock.go:203 +0x53
net.(*UDPConn).ReadMsgUDP(0x8?, {0x84c2ee000?, 0x18?, 0x479a7e?}, {0x84c15de60?, 0x84c084db8?, 0x47984e?})
        /opt/hostedtoolcache/go/1.19.1/x64/src/net/udpsock.go:191 +0x2a
github.com/nextdns/nextdns/proxy.readUDP(0x84c0742a0?, {0x84c2ee000, 0xffff, 0xffff})
        /home/runner/work/nextdns/nextdns/proxy/udp.go:142 +0x85
github.com/nextdns/nextdns/proxy.Proxy.serveUDP({{0x84c08b130, 0x1, 0x1}, {0x869e78, 0x84c094390}, {0x867ba0, 0x84c1122d0}, {0x869e78, 0x84c0943d8}, 0x1, ...}, ...)
        /home/runner/work/nextdns/nextdns/proxy/udp.go:64 +0x1f3
github.com/nextdns/nextdns/proxy.Proxy.ListenAndServe.func1({0x7cc597, 0x3})
        /home/runner/work/nextdns/nextdns/proxy/proxy.go:120 +0x345
created by github.com/nextdns/nextdns/proxy.Proxy.ListenAndServe
        /home/runner/work/nextdns/nextdns/proxy/proxy.go:112 +0x670

goroutine 8 [IO wait, 8 minutes]:
internal/poll.runtime_pollWait(0x8539645f0, 0x72)
        /opt/hostedtoolcache/go/1.19.1/x64/src/runtime/netpoll.go:305 +0x89
internal/poll.(*pollDesc).wait(0x84c024100?, 0x447cb5?, 0x0)
        /opt/hostedtoolcache/go/1.19.1/x64/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
        /opt/hostedtoolcache/go/1.19.1/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0x84c024100)
        /opt/hostedtoolcache/go/1.19.1/x64/src/internal/poll/fd_unix.go:614 +0x234
net.(*netFD).accept(0x84c024100)
        /opt/hostedtoolcache/go/1.19.1/x64/src/net/fd_unix.go:172 +0x35
net.(*TCPListener).accept(0x84c010078)
        /opt/hostedtoolcache/go/1.19.1/x64/src/net/tcpsock_posix.go:142 +0x28
net.(*TCPListener).Accept(0x84c010078)
        /opt/hostedtoolcache/go/1.19.1/x64/src/net/tcpsock.go:288 +0x3d
github.com/nextdns/nextdns/proxy.Proxy.serveTCP({{0x84c08b130, 0x1, 0x1}, {0x869e78, 0x84c094390}, {0x867ba0, 0x84c1122d0}, {0x869e78, 0x84c0943d8}, 0x1, ...}, ...)
        /home/runner/work/nextdns/nextdns/proxy/tcp.go:30 +0x62
github.com/nextdns/nextdns/proxy.Proxy.ListenAndServe.func2({0x7cc597, 0x3})
        /home/runner/work/nextdns/nextdns/proxy/proxy.go:137 +0x345
created by github.com/nextdns/nextdns/proxy.Proxy.ListenAndServe
        /home/runner/work/nextdns/nextdns/proxy/proxy.go:129 +0x870

goroutine 21 [IO wait]:
internal/poll.runtime_pollWait(0x8539646e0, 0x72)
        /opt/hostedtoolcache/go/1.19.1/x64/src/runtime/netpoll.go:305 +0x89
internal/poll.(*pollDesc).wait(0x84c099100?, 0x84c1a2000?, 0x0)
        /opt/hostedtoolcache/go/1.19.1/x64/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
        /opt/hostedtoolcache/go/1.19.1/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).ReadFromInet4(0x84c099100, {0x84c1a2000, 0x10000, 0x10000}, 0x801588?)
        /opt/hostedtoolcache/go/1.19.1/x64/src/internal/poll/fd_unix.go:250 +0x1e5
net.(*netFD).readFromInet4(0x84c099100, {0x84c1a2000?, 0x0?, 0x0?}, 0x853964708?)
        /opt/hostedtoolcache/go/1.19.1/x64/src/net/fd_posix.go:66 +0x29
net.(*UDPConn).readFrom(0x84c0bdd90?, {0x84c1a2000?, 0x84c099100?, 0x84c0bdd80?}, 0x84c0bdf08)
        /opt/hostedtoolcache/go/1.19.1/x64/src/net/udpsock_posix.go:52 +0x1b8
net.(*UDPConn).readFromUDP(0x84c0a4050, {0x84c1a2000?, 0xa8bf40?, 0xa8bf40?}, 0x0?)
        /opt/hostedtoolcache/go/1.19.1/x64/src/net/udpsock.go:149 +0x31
net.(*UDPConn).ReadFromUDP(...)
        /opt/hostedtoolcache/go/1.19.1/x64/src/net/udpsock.go:141
github.com/nextdns/nextdns/discovery.(*MDNS).read(0x84c08d3b0, {0x72c76e?, 0x86a8b8?}, 0x84c0a4050)
        /home/runner/work/nextdns/nextdns/discovery/mdns.go:197 +0x10b
created by github.com/nextdns/nextdns/discovery.(*MDNS).Start
        /home/runner/work/nextdns/nextdns/discovery/mdns.go:79 +0x365

goroutine 22 [IO wait]:
internal/poll.runtime_pollWait(0x853964410, 0x72)
        /opt/hostedtoolcache/go/1.19.1/x64/src/runtime/netpoll.go:305 +0x89
internal/poll.(*pollDesc).wait(0x84c099780?, 0x84c1b2000?, 0x0)
        /opt/hostedtoolcache/go/1.19.1/x64/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
        /opt/hostedtoolcache/go/1.19.1/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).ReadFromInet6(0x84c099780, {0x84c1b2000, 0x10000, 0x10000}, 0x801588?)
        /opt/hostedtoolcache/go/1.19.1/x64/src/internal/poll/fd_unix.go:277 +0x1e5
net.(*netFD).readFromInet6(0x84c099780, {0x84c1b2000?, 0x0?, 0x0?}, 0x853964438?)
        /opt/hostedtoolcache/go/1.19.1/x64/src/net/fd_posix.go:72 +0x29
net.(*UDPConn).readFrom(0x84c135d90?, {0x84c1b2000?, 0x84c099780?, 0x84c135d80?}, 0x84c135f08)
        /opt/hostedtoolcache/go/1.19.1/x64/src/net/udpsock_posix.go:59 +0x85
net.(*UDPConn).readFromUDP(0x84c0a4060, {0x84c1b2000?, 0xa8bf40?, 0xa8bf40?}, 0x0?)
        /opt/hostedtoolcache/go/1.19.1/x64/src/net/udpsock.go:149 +0x31
net.(*UDPConn).ReadFromUDP(...)
        /opt/hostedtoolcache/go/1.19.1/x64/src/net/udpsock.go:141
github.com/nextdns/nextdns/discovery.(*MDNS).read(0x84c08d3b0, {0x0?, 0x0?}, 0x84c0a4060)
        /home/runner/work/nextdns/nextdns/discovery/mdns.go:197 +0x10b
created by github.com/nextdns/nextdns/discovery.(*MDNS).Start
        /home/runner/work/nextdns/nextdns/discovery/mdns.go:83 +0x4db

goroutine 23 [chan receive, 8 minutes]:
github.com/nextdns/nextdns/discovery.(*MDNS).Start.func1()
        /home/runner/work/nextdns/nextdns/discovery/mdns.go:116 +0x1ed
created by github.com/nextdns/nextdns/discovery.(*MDNS).Start
        /home/runner/work/nextdns/nextdns/discovery/mdns.go:94 +0x67e

goroutine 318 [IO wait]:
internal/poll.runtime_pollWait(0x853963c90, 0x72)
        /opt/hostedtoolcache/go/1.19.1/x64/src/runtime/netpoll.go:305 +0x89
internal/poll.(*pollDesc).wait(0x84c024700?, 0x84c25f000?, 0x0)
        /opt/hostedtoolcache/go/1.19.1/x64/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
        /opt/hostedtoolcache/go/1.19.1/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0x84c024700, {0x84c25f000, 0x1000, 0x1000})
        /opt/hostedtoolcache/go/1.19.1/x64/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0x84c024700, {0x84c25f000?, 0x84c25f02e?, 0xaa?})
        /opt/hostedtoolcache/go/1.19.1/x64/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0x84c0a40e0, {0x84c25f000?, 0x85395cec8?, 0x84c118898?})
        /opt/hostedtoolcache/go/1.19.1/x64/src/net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0x84c4193c8, {0x84c25f000?, 0x0?, 0x84c1c5860?})
        /opt/hostedtoolcache/go/1.19.1/x64/src/crypto/tls/conn.go:787 +0x3d
bytes.(*Buffer).ReadFrom(0x84c118978, {0x8679c0, 0x84c4193c8})
        /opt/hostedtoolcache/go/1.19.1/x64/src/bytes/buffer.go:202 +0x98
crypto/tls.(*Conn).readFromUntil(0x84c118700, {0x857855d18?, 0x84c2c6978}, 0xfd7?)
        /opt/hostedtoolcache/go/1.19.1/x64/src/crypto/tls/conn.go:809 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0x84c118700, 0x0)
        /opt/hostedtoolcache/go/1.19.1/x64/src/crypto/tls/conn.go:616 +0x116
crypto/tls.(*Conn).readRecord(...)
        /opt/hostedtoolcache/go/1.19.1/x64/src/crypto/tls/conn.go:582
crypto/tls.(*Conn).Read(0x84c118700, {0x84c30b000, 0x1000, 0x6ae420?})
        /opt/hostedtoolcache/go/1.19.1/x64/src/crypto/tls/conn.go:1287 +0x16f
bufio.(*Reader).Read(0x84c304780, {0x84c232660, 0x9, 0x6bc865?})
        /opt/hostedtoolcache/go/1.19.1/x64/src/bufio/bufio.go:237 +0x1bb
io.ReadAtLeast({0x8678c0, 0x84c304780}, {0x84c232660, 0x9, 0x9}, 0x9)
        /opt/hostedtoolcache/go/1.19.1/x64/src/io/io.go:332 +0x9a
io.ReadFull(...)
        /opt/hostedtoolcache/go/1.19.1/x64/src/io/io.go:351
net/http.http2readFrameHeader({0x84c232660?, 0x9?, 0x84c2d3b90?}, {0x8678c0?, 0x84c304780?})
        /opt/hostedtoolcache/go/1.19.1/x64/src/net/http/h2_bundle.go:1565 +0x6e
net/http.(*http2Framer).ReadFrame(0x84c232620)
        /opt/hostedtoolcache/go/1.19.1/x64/src/net/http/h2_bundle.go:1829 +0x95
net/http.(*http2clientConnReadLoop).run(0x84c1c5f98)
        /opt/hostedtoolcache/go/1.19.1/x64/src/net/http/h2_bundle.go:8875 +0x130
net/http.(*http2ClientConn).readLoop(0x84c1cc600)
        /opt/hostedtoolcache/go/1.19.1/x64/src/net/http/h2_bundle.go:8771 +0x6f
created by net/http.(*http2Transport).newClientConn
        /opt/hostedtoolcache/go/1.19.1/x64/src/net/http/h2_bundle.go:7478 +0xaaa
```

ifconfig output setup for freebsd server:

```console
nextdns@nextdns:~ $ ifconfig
em0: flags=8863<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=481209b<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM,WOL_MAGIC,VLAN_HWFILTER,NOMAP>
        ether 02:11:32:22:f5:41
        inet 192.168.4.3 netmask 0xffffff00 broadcast 192.168.4.255
        inet6 fe80::11:32ff:fe22:f541%em0 prefixlen 64 scopeid 0x1
        inet6 fdaa:REDACTED prefixlen 64 autoconf
        inet6 2600:REDACTED  prefixlen 64 autoconf
        media: Ethernet autoselect (1000baseT <full-duplex>)
        status: active
        nd6 options=23<PERFORMNUD,ACCEPT_RTADV,AUTO_LINKLOCAL>
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
        options=680003<RXCSUM,TXCSUM,LINKSTATE,RXCSUM_IPV6,TXCSUM_IPV6>
        inet6 ::1 prefixlen 128
        inet6 fe80::1%lo0 prefixlen 64 scopeid 0x2
        inet 127.0.0.1 netmask 0xff000000
        groups: lo
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
```

/etc/hosts configuration:

```console
#
# In the presence of the domain name service or NIS, this file may
# not be consulted at all; see /etc/nsswitch.conf for the resolution order.
#
#
::1                     localhost
127.0.0.1               localhost
```

**Comment by MarkToon** [comment]
Is Nextdns dead, rarely hear anything from them these days.

Apologies for kinda hacking your thread op. I'd just like to see Nextdns helping users, like they used to do.

**Comment by KenKilty** [comment]
@rs after a reboot nextdns agent reports:

```console
Jan 26 13:44:54 nextdns nextdns[690]: Starting NextDNS 1.38.0/freebsd on :53
Jan 26 13:44:54 nextdns nextdns[690]: Starting mDNS discovery
Jan 26 13:44:54 nextdns nextdns[690]: Listening on TCP/:53
Jan 26 13:44:54 nextdns nextdns[690]: Listening on UDP/:53
Jan 26 13:44:55 nextdns nextdns[690]: Connected 45.90.30.0:443 (con=836ms tls=40ms, TCP, TLS13)
Jan 26 13:44:55 nextdns nextdns[690]: Connected 104.244.209.134:443 (con=19ms tls=39ms, TCP, TLS13)
Jan 26 13:44:55 nextdns nextdns[690]: Switching endpoint: https://dns.nextdns.io#104.244.209.134,74.118.138.167,2620:11f:7000:1fe::,2607:fdc0:5:9::24e
Jan 26 13:44:59 nextdns nextdns[690]: Setting up router
Jan 26 13:44:59 nextdns nextdns[690]: Activating
nextdns@nextdns:~ $
```
The contents of ```/etc/resolve.conf```

```console
nextdns@nextdns:~ $ cat /etc/resolv.conf
# This file is managed by nextdns.
#
# Run "nextdns deactivate" to restore previous configuration.

nameserver 127.0.0.1
```
The contents of ```/etc/resolveconf.conf```

```console
nextdns@nextdns:~ $ cat /etc/resolvconf.conf
resolvconf=NO
```
After running the sledgehammer ```service netif restart``` resolv.conf and resolveconf.conf are identical.

The contents of ```/etc/resolve.conf```

```console
nextdns@nextdns:~ $ cat /etc/resolv.conf
# This file is managed by nextdns.
#
# Run "nextdns deactivate" to restore previous configuration.

nameserver 127.0.0.1
```

The contents of ```/etc/resolveconf.conf```

```console
nextdns@nextdns:~ $ cat /etc/resolvconf.conf
resolvconf=NO
```
However consistently the nextdns agent is now running correctly until the next reboot where I repeat this process. Probably should automate. :-)

```console
Jan 26 13:51:10 nextdns nextdns[690]: Query 192.X.X.X UDP AAAA REDACTED.com. (qry=36/res=12) 128ms : doh resolve: read tcp 192.X.X.X:11013->XXX.XXX.XXX.134:443: read: no route to host
Jan 26 13:51:10 nextdns nextdns[690]: Query 192.X.X.X UDP AAAA REDACTED.com. (qry=43/res=12) 988ms : doh resolve: read tcp 192.X.X.X:11013->XXX.XXX.XXX.134:443: read: no route to host
Jan 26 13:51:10 nextdns nextdns[690]: Query 192.X.X.X UDP A REDACTED.com. (qry=57/res=12) 2043ms : doh resolve: read tcp 192.X.X.X:11013->XXX.XXX.XXX.134:443: read: no route to host
Jan 26 13:51:11 nextdns nextdns[690]: Connected [2620:REDACTED::]:443 (con=20ms tls=23ms, TCP, TLS13)
nextdns@nextdns:~ $
```

**Comment by rs** [comment]
When it is blocked, do you see any process forked by the nextdns daemon? When blocked, does it just not resolve or resolution does not go through the CLI? Can you please describe the behavior more?

**Comment by KenKilty** [comment]
@rs after a reboot nextdns is configured as a router so onstart of the agent after reboot there is an activating state that I believe is registering the agent as a router to allow external requests on :53 (just my understanding versus only local requests). This activation of allowing external requests on the local network get's "stuck" so no DNS requests are processed by the DoH proxy. So any machine on the local network that attempts to connect on :53 with DNS using the IP of this FreeBSD machine fails and falls back to the public IPs for NextDNS. I have a local machine, nextdns.local, on my local network that is the DoH proxy and my Eero mesh system points to this machine first and the public NextDNS IP's as a backup.

To your question about the process tree when stuck in 'activating' in the nextdns log

```console
nextdns@nextdns:~ $ pstree
-+= 00001 root /sbin/init
 |--= 00453 root /sbin/devd
 |--= 00653 root /usr/sbin/syslogd -s
 |-+= 00675 root daemon: nextdns: daemon[676] (daemon)
 | \--- 00676 root /usr/local/sbin/nextdns run
 |--= 00713 root /usr/local/bin/qemu-ga -d -v -l /var/log/qemu-ga.log
 |--= 00738 root /usr/sbin/cron -s
 |--= 00746 root sendmail: accepting connections (sendmail)
 |--= 00749 smmsp sendmail: Queue runner@00:30:00 for /var/spool/clientmqueue (sendmail)
 |-+= 00766 root sshd: /usr/sbin/sshd [listener] 0 of 10-100 startups (sshd)
 | \-+= 00814 root sshd: nextdns [priv] (sshd)
 |   \-+- 00817 nextdns sshd: nextdns@pts/0 (sshd)
 |     \-+= 00818 nextdns -sh (sh)
 |       \-+= 00836 nextdns pstree
 |         \--- 00837 nextdns ps -axwwo user,pid,ppid,pgid,command
 |--= 00784 root ddclient - sleeping for 199 seconds (perl)
 |--= 00801 root /usr/libexec/getty Pc ttyv0
 |--= 00802 root /usr/libexec/getty Pc ttyv1
 |--= 00803 root /usr/libexec/getty Pc ttyv2
 |--= 00804 root /usr/libexec/getty Pc ttyv3
 |--= 00805 root /usr/libexec/getty Pc ttyv4
 |--= 00806 root /usr/libexec/getty Pc ttyv5
 |--= 00807 root /usr/libexec/getty Pc ttyv6
 \--= 00808 root /usr/libexec/getty Pc ttyv7
```
A local DNS lookup on the DoH FreeBSD proxy works fine:

```console
nextdns@nextdns:~ $ host freebsd.org
freebsd.org has address 96.47.72.84
freebsd.org has IPv6 address 2610:1c1:1:606c::50:15
freebsd.org mail is handled by 10 mx1.freebsd.org.
freebsd.org mail is handled by 30 mx66.freebsd.org.
```

After I cycle network again the process tree is:

```console
nextdns@nextdns:~ $ pstree
-+= 00001 root /sbin/init
 |--= 00453 root /sbin/devd
 |--= 00653 root /usr/sbin/syslogd -s
 |-+= 00675 root daemon: nextdns: daemon[676] (daemon)
 | \--- 00676 root /usr/local/sbin/nextdns run
 |--= 00713 root /usr/local/bin/qemu-ga -d -v -l /var/log/qemu-ga.log
 |--= 00738 root /usr/sbin/cron -s
 |--= 00746 root sendmail: accepting connections (sendmail)
 |--= 00749 smmsp sendmail: Queue runner@00:30:00 for /var/spool/clientmqueue (sendmail)
 |-+= 00766 root sshd: /usr/sbin/sshd [listener] 0 of 10-100 startups (sshd)
 | \-+= 00814 root sshd: nextdns [priv] (sshd)
 |   \-+- 00817 nextdns sshd: nextdns@pts/0 (sshd)
 |     \-+= 00818 nextdns -sh (sh)
 |       \-+= 01136 nextdns pstree
 |         \--- 01137 nextdns ps -axwwo user,pid,ppid,pgid,command
 |--= 00784 root ddclient - sleeping for 29 seconds (perl)
 |--= 00801 root /usr/libexec/getty Pc ttyv0
 |--= 00802 root /usr/libexec/getty Pc ttyv1
 |--= 00803 root /usr/libexec/getty Pc ttyv2
 |--= 00804 root /usr/libexec/getty Pc ttyv3
 |--= 00805 root /usr/libexec/getty Pc ttyv4
 |--= 00806 root /usr/libexec/getty Pc ttyv5
 |--= 00807 root /usr/libexec/getty Pc ttyv6
 \--= 00808 root /usr/libexec/getty Pc ttyv7
```

**Comment by rs** [comment]
Note that activate is only to setup the local system to use the CLI for its own resolution. In the context of a DNS server like in your case, you do not need activate.

Just to make sure, if you do not auto-activate and do not call activate manual, does it serve DNS queries for your network correctly?

**Comment by KenKilty** [comment]
@rs I did not realize activate was only for local system. Apologies if I missed this in the documentation. Disabling activate via config ```auto-activate false``` resulted in a the agent starting without hanging. Thank you! Local resolution appears to work fine as shown below.

```console
nextdns@nextdns:~ $ host freebsd.org
freebsd.org has address 96.47.72.84
freebsd.org has IPv6 address 2610:1c1:1:606c::50:15
freebsd.org mail is handled by 10 mx1.freebsd.org.
freebsd.org mail is handled by 30 mx66.freebsd.org.
```
